name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Build Docker Image for Backend
      - name: Build Docker Image for Backend
        run: docker build --file backend/Dockerfile --tag backend-build:latest ./backend

      # Step 5: Run Maven Tests Inside Docker Container
      - name: Run Backend Tests
        run: |
          docker run --rm backend-build:latest mvn test -Dsurefire.useFile=false -e -X

      # Step 6: Print Test Output on Failure
      - name: Print Test Output on Failure
        if: failure()
        run: docker logs backend-build

      # Step 7: Build Production Docker Image for Backend
      - name: Build Production Docker Image for Backend
        if: success()
        run: docker build --file backend/Dockerfile --tag backend:latest ./backend
