name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image for Backend
        run: docker build --file Dockerfile --tag backend-build:latest .

      - name: Run Backend Tests
        run: |
          docker run --rm backend-build:latest mvn test -Dsurefire.useFile=false -e -X

      - name: Print Test Output on Failure
        if: failure()
        run: docker logs $(docker ps -aq --filter "ancestor=backend-build:latest" --latest)

      - name: Build Production Docker Image for Backend
        if: success()
        run: docker build --file Dockerfile --tag backend:latest .
